### ISSUE TITLE
todo: improving example organization

### ISSUE THREAD

**Issue by ranwez** [GE2POP/GeCKO#1]
- [ ] Creating a subfolder per example each with a readme file and a configuration file (or a SGE and SLURM one if needed) 
- [ ] Using relative paths in the configuration files of the examples, so that they work when copied into the WORKFLOW folder of new users
- [ ] Clarifying what have to be done regarding SLURM/SGE environment
- [ ] Adding configuration file, and information, for running pipeline on a PC
